-- Run this in the NEW Supabase project SQL editor (fadatnutpfnhxwctyvdt)
-- Creates cs_vendors table with full schema matching the old project

CREATE TABLE IF NOT EXISTS cs_vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  website text NOT NULL UNIQUE,
  source text,
  mission text,
  usp text,
  pricing text,
  free_trial boolean,
  soc2 boolean,
  founded text,
  use_cases text[],
  lifecycle_stages text[],
  raw_description text,
  first_seen date DEFAULT CURRENT_DATE,
  last_enriched_at timestamptz,
  last_enriched_pipeline text,
  enrichment_count integer DEFAULT 0,
  enrichment_pipeline_counts jsonb DEFAULT '{}',
  last_updated timestamptz DEFAULT now(),
  is_new boolean DEFAULT true,
  icp text[] DEFAULT '{}',
  case_studies text[] DEFAULT '{}',
  customers text[] DEFAULT '{}',
  value_statements text[] DEFAULT '{}',
  evidence_urls text[] DEFAULT '{}',
  directory_fit text,
  directory_category text,
  include_in_directory boolean DEFAULT false,
  confidence text,
  icp_buyer jsonb DEFAULT '[]',
  products jsonb DEFAULT '[]',
  leadership jsonb DEFAULT '[]',
  company_hq text,
  contact_email text,
  contact_page_url text,
  demo_url text,
  help_center_url text,
  support_url text,
  about_url text,
  team_url text,
  integration_categories text[] DEFAULT '{}',
  integrations text[] DEFAULT '{}',
  support_signals text[] DEFAULT '{}',
  case_study_details jsonb DEFAULT '[]',
  auto_directory_fit text,
  auto_directory_category text,
  auto_include_in_directory boolean,
  directory_decision_source text,
  directory_reasoning text[],
  hq_address text,
  source_urls text[],
  compliance text[],
  ceo_name text,
  phone_numbers text[],
  contact_emails text[],
  developer_docs_url text,
  integration_taxonomy jsonb,
  external_enrichment jsonb,
  testimonials text[],
  blog_posts text[],
  llm_directory_fit text,
  llm_directory_category text,
  llm_include_in_directory boolean,
  ceo_linkedin text,
  youtube_channel_url text,
  funding_stage text,
  total_funding text,
  use_case_details jsonb DEFAULT '[]',
  has_public_pricing_page boolean,
  pricing_source text,
  g2_url text,
  g2_rating numeric,
  g2_review_count integer,
  g2_market_segment text,
  g2_categories text[] DEFAULT '{}',
  case_study_signals text[] DEFAULT ARRAY[]::text[],
  raw_crawl_blob text,
  crawl_page_count integer,
  crawl_completed_at timestamptz
);
